### PR TITLE
Fix dependency format in metadata.json

### PR DESCRIPTION
**Pull request by s12v**
Resolves https://github.com/artberri/puppet-nvm/issues/8

### CODE REVIEW

**Comment by marcgascon** [comment]
+1

**Comment by martynas-foodpanda** [comment]
👍  Thanks!

**Comment by jaymecd** [comment]
👍

**Comment by s12v** [comment]
@artberri, could you please publish a new release with this change on forge?

**Comment by artberri** [comment]
@s12v I'll try to do it Today

**Comment by s12v** [comment]
@artberri, sorry to bother, could you please publish a new release?

**Pull request merged**
